spring:
  profiles:
    active: dev

---

server:
  port: 8080
spring:
  profiles: dev


spring:
   application:
    name: microservicecloud-user
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/jpa                    # 数据库名称
    username: root
    password: root

    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间

   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: microservicecloud-user8080
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: tlw-microservicecloud
  company.name: www.tlw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server:
  port: 8081
spring:
  profiles: prod


spring:
   application:
    name: microservicecloud-user
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/jpa01                    # 数据库名称
    username: root
    password: root

    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间

   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8002/eureka
  instance:
    instance-id: microservicecloud-user8081
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: tlw-microservicecloud
  company.name: www.tlw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$